trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  ciPipeline: 'ci-api-main'
  functionAppName: 'dstudio-api-alpha'
  packageName: 'API'
  project: 'DStudio'

resources:
  pipelines:
    - pipeline: ciApiMain
      source: 'ci-api-main'
      trigger: true

steps:
  - template: ../../../DevOps/cd-dotNet8-AzureFunction-template.yml